<?php

use yii\db\Migration;

/**
 * Class m221007_161621_test_m
 */
class m221007_161621_test_m extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m221007_161621_test_m cannot be reverted.\n";

        return false;
    }

//    public function createIndex($name, $table, $columns, $unique = false)
//    {
//        parent::createIndex($name, $table, $columns, $unique); // TODO: Change the autogenerated stub
//    }

public function addForeignKey($name, $table, $columns, $refTable, $refColumns, $delete = null, $update = null)
{
    parent::addForeignKey($name, $table, $columns, $refTable, $refColumns, $delete, $update); // TODO: Change the autogenerated stub
}

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m221007_161621_test_m cannot be reverted.\n";

        return false;
    }
    */
}
